name: canvas-nesting-doll-peer-reviews
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.9.0
  - python-dotenv
  - termcolor
  - requests
  - jupyter
  - pandas=1.5.3
  - pip
  - pip:
      - canvasapi>=2.0.0
